[build]
  base = "drinkit-delivery"
  command = "npm run build"
  publish = ".next"

[build.environment]
  ALFA_SBP_GATEWAY_URL = "https://payment.alfabank.ru/payment/rest"
  ALFA_SBP_RETURN_URL = "https://maru-delivery.netlify.app/checkout"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    CDN-Cache-Control = "no-store"
    Netlify-CDN-Cache-Control = "no-store"
